/** Generated by itemis CREATE code generator. */

#ifndef BUTTONS_REQUIRED_H_
#define BUTTONS_REQUIRED_H_

#include "sc_types.h"
#include "buttons.h"

#ifdef __cplusplus
extern "C"
{
#endif 

/*! \file
This header defines prototypes for all functions that are required by the state machine implementation.

This is a state machine uses time events which require access to a timing service. Thus the function prototypes:
- buttons_set_timer and
- buttons_unset_timer
are defined.
This state machine makes use of operations declared in the state machines interface or internal scopes. Thus the function prototypes:
- buttons_pressed
- buttons_released
- buttons_tipped
- buttons_selected
are defined.

These functions will be called during a 'run to completion step' (runCycle) of the statechart. 
There are some constraints that have to be considered for the implementation of these functions:
- never call the statechart API functions from within these functions.
- make sure that the execution time is as short as possible.

*/

extern void buttons_pressed(const Buttons* handle, const uint16_t btn);
extern void buttons_released(const Buttons* handle, const uint16_t btn);
extern void buttons_tipped(const Buttons* handle, const uint16_t btn);
extern void buttons_selected(const Buttons* handle, const uint16_t btn);



/*! 
This function has to set up timers for the time events that are required by the state machine.
It will be called for each time event that is relevant for a state when a state will be entered.
\param evid An unique identifier of the event.
\time_ms The time in milliseconds
\periodic Indicates the the time event must be raised periodically until the timer is unset 
*/
extern void buttons_set_timer(Buttons* handle, const sc_eventid evid, const sc_integer time_ms, const sc_boolean periodic);

/*! 
This function has to unset timers for the time events that are required by the state machine.
It will be called for each time event that is relevant for a state when a state will be left.
\param evid An unique identifier of the event.
*/
extern void buttons_unset_timer(Buttons* handle, const sc_eventid evid);



#ifdef __cplusplus
}
#endif 

#endif /* BUTTONS_REQUIRED_H_ */
