/** Generated by itemis CREATE code generator. */


#include "../Inc/sc_types.h"

#include "../Inc/blink.h"
#include "../Inc/blink_required.h"

/*! \file
Implementation of the state machine 'blink'
*/

#ifndef SC_UNUSED
#define SC_UNUSED(P) (void)(P)
#endif

/* prototypes of all internal functions */

/*! State machine reactions. */
static sc_integer react(Blink* handle, const sc_integer transitioned_before);

/*! The reactions of state Light. */
static sc_integer main_Light_react(Blink* handle, const sc_integer transitioned_before);

/*! The reactions of state On1. */
static sc_integer main_Light__region0_On1_react(Blink* handle, const sc_integer transitioned_before);

/*! The reactions of state On2. */
static sc_integer main_Light__region0_On2_react(Blink* handle, const sc_integer transitioned_before);

/*! The reactions of state On3. */
static sc_integer main_Light__region0_On3_react(Blink* handle, const sc_integer transitioned_before);

/*! The reactions of state On4. */
static sc_integer main_Light__region0_On4_react(Blink* handle, const sc_integer transitioned_before);

/*! The reactions of state On5. */
static sc_integer main_Light__region0_On5_react(Blink* handle, const sc_integer transitioned_before);

/*! The reactions of state Dark. */
static sc_integer main_Dark_react(Blink* handle, const sc_integer transitioned_before);


static void clear_in_events(Blink* handle);

static void micro_step(Blink* handle);

/*! Performs a 'run to completion' step. */
static void run_cycle(Blink* handle);






static void blink_eventqueue_init(blink_eventqueue * eq, blink_event *buffer, sc_integer capacity);
static sc_integer blink_eventqueue_size(blink_eventqueue * eq);
static void blink_event_init(blink_event * ev, BlinkEventID name);
static blink_event blink_eventqueue_pop(blink_eventqueue * eq);
static sc_boolean blink_eventqueue_push(blink_eventqueue * eq, blink_event ev);
static void blink_add_event_to_queue(blink_eventqueue * eq, BlinkEventID name);
static sc_boolean blink_dispatch_event(Blink* handle, const blink_event * event);
static blink_event blink_get_next_event(Blink* handle);
static sc_boolean blink_dispatch_next_event(Blink* handle);
static BlinkEventID blink_get_timed_event_name(Blink* handle, sc_eventid evid);


void blink_init(Blink* handle)
{
	sc_integer i;
	
	for (i = 0; i < BLINK_MAX_ORTHOGONAL_STATES; ++i)
	{
		handle->stateConfVector[i] = Blink_last_state;
	}
	
				
	clear_in_events(handle);
	
	sc_observable_init(&handle->iface.cycleCompleted);
	
	/* Default init sequence for statechart blink */
	blink_set_t_light(handle, 500);
	blink_set_t_dark(handle, 500);
	
	handle->isExecuting = bool_false;
	blink_eventqueue_init(&handle->in_event_queue, handle->in_buffer, BLINK_IN_EVENTQUEUE_BUFFERSIZE);
}

void blink_enter(Blink* handle)
{
	/* Activates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default enter sequence for statechart blink */
	/* 'default' enter sequence for region main */
	/* Default react sequence for initial entry  */
	/* 'default' enter sequence for state Light */
	/* 'default' enter sequence for region  */
	/* Default react sequence for initial entry  */
	/* 'default' enter sequence for state On1 */
	/* Entry action for state 'On1'. */
	blink_set_timer(handle, (sc_eventid) &(handle->timeEvents.blink_main_Light__region0_On1_tev0_raised) , ((handle->iface.t_light / 5)), bool_false);
	blink_switchOn(handle,1);
	handle->stateConfVector[0] = Blink_main_Light__region0_On1;
	handle->isExecuting = bool_false;
}

void blink_exit(Blink* handle)
{
	/* Deactivates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default exit sequence for statechart blink */
	/* Default exit sequence for region main */
	/* Handle exit of all possible states (of blink.main) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Blink_main_Light__region0_On1 :
		{
			/* Default exit sequence for state On1 */
			handle->stateConfVector[0] = Blink_last_state;
			/* Exit action for state 'On1'. */
			blink_unset_timer(handle, (sc_eventid) &(handle->timeEvents.blink_main_Light__region0_On1_tev0_raised) );		
			break;
		}
		case Blink_main_Light__region0_On2 :
		{
			/* Default exit sequence for state On2 */
			handle->stateConfVector[0] = Blink_last_state;
			/* Exit action for state 'On2'. */
			blink_unset_timer(handle, (sc_eventid) &(handle->timeEvents.blink_main_Light__region0_On2_tev0_raised) );		
			break;
		}
		case Blink_main_Light__region0_On3 :
		{
			/* Default exit sequence for state On3 */
			handle->stateConfVector[0] = Blink_last_state;
			/* Exit action for state 'On3'. */
			blink_unset_timer(handle, (sc_eventid) &(handle->timeEvents.blink_main_Light__region0_On3_tev0_raised) );		
			break;
		}
		case Blink_main_Light__region0_On4 :
		{
			/* Default exit sequence for state On4 */
			handle->stateConfVector[0] = Blink_last_state;
			/* Exit action for state 'On4'. */
			blink_unset_timer(handle, (sc_eventid) &(handle->timeEvents.blink_main_Light__region0_On4_tev0_raised) );		
			break;
		}
		case Blink_main_Light__region0_On5 :
		{
			/* Default exit sequence for state On5 */
			handle->stateConfVector[0] = Blink_last_state;
			/* Exit action for state 'On5'. */
			blink_unset_timer(handle, (sc_eventid) &(handle->timeEvents.blink_main_Light__region0_On5_tev0_raised) );		
			break;
		}
		case Blink_main_Dark :
		{
			/* Default exit sequence for state Dark */
			handle->stateConfVector[0] = Blink_last_state;
			/* Exit action for state 'Dark'. */
			blink_unset_timer(handle, (sc_eventid) &(handle->timeEvents.blink_main_Dark_tev0_raised) );		
			break;
		}
		default: 
			/* do nothing */
			break;
	}
	/* Exit action for state 'blink'. */
	blink_switchOff(handle,1);
	blink_switchOff(handle,2);
	blink_switchOff(handle,3);
	handle->isExecuting = bool_false;
}

/*!
Can be used by the client code to trigger a run to completion step without raising an event.
*/
void blink_trigger_without_event(Blink* handle) {
	run_cycle(handle);
}


sc_boolean blink_is_active(const Blink* handle)
{
	sc_boolean result = bool_false;
	sc_integer i;
	
	for(i = 0; i < BLINK_MAX_ORTHOGONAL_STATES; i++)
	{
		result = result || handle->stateConfVector[i] != Blink_last_state;
	}
	
	return result;
}

/* 
 * Always returns 'false' since this state machine can never become final.
 */
sc_boolean blink_is_final(const Blink* handle)
{
	SC_UNUSED(handle);
	return bool_false;
}

void blink_raise_time_event(Blink* handle, sc_eventid evid)
{
	if ( ((sc_intptr_t)evid) >= ((sc_intptr_t)&(handle->timeEvents))
		&&  ((sc_intptr_t)evid) < ((sc_intptr_t)&(handle->timeEvents)) + (unsigned)sizeof(BlinkTimeEvents))
	{
		blink_add_event_to_queue(&(handle->in_event_queue), blink_get_timed_event_name(handle, evid));
		run_cycle(handle);
	}
}

sc_boolean blink_is_state_active(const Blink* handle, BlinkStates state)
{
	sc_boolean result = bool_false;
	switch (state)
	{
		case Blink_main_Light :
			result = (sc_boolean) (handle->stateConfVector[SCVI_BLINK_MAIN_LIGHT] >= Blink_main_Light
				&& handle->stateConfVector[SCVI_BLINK_MAIN_LIGHT] <= Blink_main_Light__region0_On5);
				break;
		case Blink_main_Light__region0_On1 :
			result = (sc_boolean) (handle->stateConfVector[SCVI_BLINK_MAIN_LIGHT__REGION0_ON1] == Blink_main_Light__region0_On1
			);
				break;
		case Blink_main_Light__region0_On2 :
			result = (sc_boolean) (handle->stateConfVector[SCVI_BLINK_MAIN_LIGHT__REGION0_ON2] == Blink_main_Light__region0_On2
			);
				break;
		case Blink_main_Light__region0_On3 :
			result = (sc_boolean) (handle->stateConfVector[SCVI_BLINK_MAIN_LIGHT__REGION0_ON3] == Blink_main_Light__region0_On3
			);
				break;
		case Blink_main_Light__region0_On4 :
			result = (sc_boolean) (handle->stateConfVector[SCVI_BLINK_MAIN_LIGHT__REGION0_ON4] == Blink_main_Light__region0_On4
			);
				break;
		case Blink_main_Light__region0_On5 :
			result = (sc_boolean) (handle->stateConfVector[SCVI_BLINK_MAIN_LIGHT__REGION0_ON5] == Blink_main_Light__region0_On5
			);
				break;
		case Blink_main_Dark :
			result = (sc_boolean) (handle->stateConfVector[SCVI_BLINK_MAIN_DARK] == Blink_main_Dark
			);
				break;
			default:
				result = bool_false;
				break;
		}
		return result;
	}

static void clear_in_events(Blink* handle)
{
	handle->timeEvents.blink_main_Light__region0_On1_tev0_raised = bool_false;
	handle->timeEvents.blink_main_Light__region0_On2_tev0_raised = bool_false;
	handle->timeEvents.blink_main_Light__region0_On3_tev0_raised = bool_false;
	handle->timeEvents.blink_main_Light__region0_On4_tev0_raised = bool_false;
	handle->timeEvents.blink_main_Light__region0_On5_tev0_raised = bool_false;
	handle->timeEvents.blink_main_Dark_tev0_raised = bool_false;
}

static void micro_step(Blink* handle)
{
	switch(handle->stateConfVector[ 0 ])
	{
		case Blink_main_Light__region0_On1 :
		{
			main_Light__region0_On1_react(handle,-1);
			break;
		}
		case Blink_main_Light__region0_On2 :
		{
			main_Light__region0_On2_react(handle,-1);
			break;
		}
		case Blink_main_Light__region0_On3 :
		{
			main_Light__region0_On3_react(handle,-1);
			break;
		}
		case Blink_main_Light__region0_On4 :
		{
			main_Light__region0_On4_react(handle,-1);
			break;
		}
		case Blink_main_Light__region0_On5 :
		{
			main_Light__region0_On5_react(handle,-1);
			break;
		}
		case Blink_main_Dark :
		{
			main_Dark_react(handle,-1);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
}

static void run_cycle(Blink* handle)
{
	/* Performs a 'run to completion' step. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	blink_dispatch_next_event(handle);
	do
	{ 
		micro_step(handle);
		clear_in_events(handle);
	} while (blink_dispatch_next_event(handle) == bool_true);
	handle->isExecuting = bool_false;
}



sc_observable* blink_get_cycleCompleted(Blink* handle)
{
	return &handle->iface.cycleCompleted;
}

sc_integer blink_get_t_light(const Blink* handle)
{
	return handle->iface.t_light;
}
void blink_set_t_light(Blink* handle, sc_integer value)
{
	handle->iface.t_light = value;
}
sc_integer blink_get_t_dark(const Blink* handle)
{
	return handle->iface.t_dark;
}
void blink_set_t_dark(Blink* handle, sc_integer value)
{
	handle->iface.t_dark = value;
}



/* implementations of all internal functions */


static sc_integer react(Blink* handle, const sc_integer transitioned_before)
{
	/* State machine reactions. */
	SC_UNUSED(handle);
	return transitioned_before;
}

static sc_integer main_Light_react(Blink* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Light. */
 			sc_integer transitioned_after = transitioned_before;
	/* Always execute local reactions. */
	transitioned_after = react(handle,transitioned_before);
	return transitioned_after;
}

static sc_integer main_Light__region0_On1_react(Blink* handle, const sc_integer transitioned_before)
{
	/* The reactions of state On1. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->timeEvents.blink_main_Light__region0_On1_tev0_raised == bool_true)
		{ 
			/* Default exit sequence for state On1 */
			handle->stateConfVector[0] = Blink_last_state;
			/* Exit action for state 'On1'. */
			blink_unset_timer(handle, (sc_eventid) &(handle->timeEvents.blink_main_Light__region0_On1_tev0_raised) );		
			handle->timeEvents.blink_main_Light__region0_On1_tev0_raised = bool_false;
			/* 'default' enter sequence for state On2 */
			/* Entry action for state 'On2'. */
			blink_set_timer(handle, (sc_eventid) &(handle->timeEvents.blink_main_Light__region0_On2_tev0_raised) , ((handle->iface.t_light / 5)), bool_false);
			blink_switchOn(handle,2);
			handle->stateConfVector[0] = Blink_main_Light__region0_On2;
			main_Light_react(handle,0);
			transitioned_after = 0;
		} 
	} 
	/* If no transition was taken */
	if ((transitioned_after) == (transitioned_before))
	{ 
		/* then execute local reactions. */
		transitioned_after = main_Light_react(handle,transitioned_before);
	} 
	return transitioned_after;
}

static sc_integer main_Light__region0_On2_react(Blink* handle, const sc_integer transitioned_before)
{
	/* The reactions of state On2. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->timeEvents.blink_main_Light__region0_On2_tev0_raised == bool_true)
		{ 
			/* Default exit sequence for state On2 */
			handle->stateConfVector[0] = Blink_last_state;
			/* Exit action for state 'On2'. */
			blink_unset_timer(handle, (sc_eventid) &(handle->timeEvents.blink_main_Light__region0_On2_tev0_raised) );		
			handle->timeEvents.blink_main_Light__region0_On2_tev0_raised = bool_false;
			/* 'default' enter sequence for state On3 */
			/* Entry action for state 'On3'. */
			blink_set_timer(handle, (sc_eventid) &(handle->timeEvents.blink_main_Light__region0_On3_tev0_raised) , ((handle->iface.t_light / 5)), bool_false);
			blink_switchOn(handle,3);
			handle->stateConfVector[0] = Blink_main_Light__region0_On3;
			main_Light_react(handle,0);
			transitioned_after = 0;
		} 
	} 
	/* If no transition was taken */
	if ((transitioned_after) == (transitioned_before))
	{ 
		/* then execute local reactions. */
		transitioned_after = main_Light_react(handle,transitioned_before);
	} 
	return transitioned_after;
}

static sc_integer main_Light__region0_On3_react(Blink* handle, const sc_integer transitioned_before)
{
	/* The reactions of state On3. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->timeEvents.blink_main_Light__region0_On3_tev0_raised == bool_true)
		{ 
			/* Default exit sequence for state On3 */
			handle->stateConfVector[0] = Blink_last_state;
			/* Exit action for state 'On3'. */
			blink_unset_timer(handle, (sc_eventid) &(handle->timeEvents.blink_main_Light__region0_On3_tev0_raised) );		
			handle->timeEvents.blink_main_Light__region0_On3_tev0_raised = bool_false;
			/* 'default' enter sequence for state On4 */
			/* Entry action for state 'On4'. */
			blink_set_timer(handle, (sc_eventid) &(handle->timeEvents.blink_main_Light__region0_On4_tev0_raised) , ((handle->iface.t_light / 5)), bool_false);
			blink_switchOff(handle,1);
			handle->stateConfVector[0] = Blink_main_Light__region0_On4;
			main_Light_react(handle,0);
			transitioned_after = 0;
		} 
	} 
	/* If no transition was taken */
	if ((transitioned_after) == (transitioned_before))
	{ 
		/* then execute local reactions. */
		transitioned_after = main_Light_react(handle,transitioned_before);
	} 
	return transitioned_after;
}

static sc_integer main_Light__region0_On4_react(Blink* handle, const sc_integer transitioned_before)
{
	/* The reactions of state On4. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->timeEvents.blink_main_Light__region0_On4_tev0_raised == bool_true)
		{ 
			/* Default exit sequence for state On4 */
			handle->stateConfVector[0] = Blink_last_state;
			/* Exit action for state 'On4'. */
			blink_unset_timer(handle, (sc_eventid) &(handle->timeEvents.blink_main_Light__region0_On4_tev0_raised) );		
			handle->timeEvents.blink_main_Light__region0_On4_tev0_raised = bool_false;
			/* 'default' enter sequence for state On5 */
			/* Entry action for state 'On5'. */
			blink_set_timer(handle, (sc_eventid) &(handle->timeEvents.blink_main_Light__region0_On5_tev0_raised) , ((handle->iface.t_light / 5)), bool_false);
			blink_switchOff(handle,2);
			handle->stateConfVector[0] = Blink_main_Light__region0_On5;
			main_Light_react(handle,0);
			transitioned_after = 0;
		} 
	} 
	/* If no transition was taken */
	if ((transitioned_after) == (transitioned_before))
	{ 
		/* then execute local reactions. */
		transitioned_after = main_Light_react(handle,transitioned_before);
	} 
	return transitioned_after;
}

static sc_integer main_Light__region0_On5_react(Blink* handle, const sc_integer transitioned_before)
{
	/* The reactions of state On5. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->timeEvents.blink_main_Light__region0_On5_tev0_raised == bool_true)
		{ 
			/* Default exit sequence for state Light */
			/* Default exit sequence for region  */
			/* Handle exit of all possible states (of blink.main.Light._region0) at position 0... */
			switch(handle->stateConfVector[ 0 ])
			{
				case Blink_main_Light__region0_On1 :
				{
					/* Default exit sequence for state On1 */
					handle->stateConfVector[0] = Blink_last_state;
					/* Exit action for state 'On1'. */
					blink_unset_timer(handle, (sc_eventid) &(handle->timeEvents.blink_main_Light__region0_On1_tev0_raised) );		
					break;
				}
				case Blink_main_Light__region0_On2 :
				{
					/* Default exit sequence for state On2 */
					handle->stateConfVector[0] = Blink_last_state;
					/* Exit action for state 'On2'. */
					blink_unset_timer(handle, (sc_eventid) &(handle->timeEvents.blink_main_Light__region0_On2_tev0_raised) );		
					break;
				}
				case Blink_main_Light__region0_On3 :
				{
					/* Default exit sequence for state On3 */
					handle->stateConfVector[0] = Blink_last_state;
					/* Exit action for state 'On3'. */
					blink_unset_timer(handle, (sc_eventid) &(handle->timeEvents.blink_main_Light__region0_On3_tev0_raised) );		
					break;
				}
				case Blink_main_Light__region0_On4 :
				{
					/* Default exit sequence for state On4 */
					handle->stateConfVector[0] = Blink_last_state;
					/* Exit action for state 'On4'. */
					blink_unset_timer(handle, (sc_eventid) &(handle->timeEvents.blink_main_Light__region0_On4_tev0_raised) );		
					break;
				}
				case Blink_main_Light__region0_On5 :
				{
					/* Default exit sequence for state On5 */
					handle->stateConfVector[0] = Blink_last_state;
					/* Exit action for state 'On5'. */
					blink_unset_timer(handle, (sc_eventid) &(handle->timeEvents.blink_main_Light__region0_On5_tev0_raised) );		
					break;
				}
				default: 
					/* do nothing */
					break;
			}
			handle->timeEvents.blink_main_Light__region0_On5_tev0_raised = bool_false;
			/* 'default' enter sequence for state Dark */
			/* Entry action for state 'Dark'. */
			blink_set_timer(handle, (sc_eventid) &(handle->timeEvents.blink_main_Dark_tev0_raised) , handle->iface.t_dark, bool_false);
			blink_switchOff(handle,3);
			sc_observable_next(&handle->iface.cycleCompleted);
			handle->stateConfVector[0] = Blink_main_Dark;
			react(handle,0);
			transitioned_after = 0;
		} 
	} 
	/* If no transition was taken */
	if ((transitioned_after) == (transitioned_before))
	{ 
		/* then execute local reactions. */
		transitioned_after = main_Light_react(handle,transitioned_before);
	} 
	return transitioned_after;
}

static sc_integer main_Dark_react(Blink* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Dark. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->timeEvents.blink_main_Dark_tev0_raised == bool_true)
		{ 
			/* Default exit sequence for state Dark */
			handle->stateConfVector[0] = Blink_last_state;
			/* Exit action for state 'Dark'. */
			blink_unset_timer(handle, (sc_eventid) &(handle->timeEvents.blink_main_Dark_tev0_raised) );		
			handle->timeEvents.blink_main_Dark_tev0_raised = bool_false;
			/* 'default' enter sequence for state Light */
			/* 'default' enter sequence for region  */
			/* Default react sequence for initial entry  */
			/* 'default' enter sequence for state On1 */
			/* Entry action for state 'On1'. */
			blink_set_timer(handle, (sc_eventid) &(handle->timeEvents.blink_main_Light__region0_On1_tev0_raised) , ((handle->iface.t_light / 5)), bool_false);
			blink_switchOn(handle,1);
			handle->stateConfVector[0] = Blink_main_Light__region0_On1;
			react(handle,0);
			transitioned_after = 0;
		} 
	} 
	/* If no transition was taken */
	if ((transitioned_after) == (transitioned_before))
	{ 
		/* then execute local reactions. */
		transitioned_after = react(handle,transitioned_before);
	} 
	return transitioned_after;
}




static void blink_eventqueue_init(blink_eventqueue * eq, blink_event *buffer, sc_integer capacity)
{
	eq->events = buffer;
	eq->capacity = capacity;
	eq->push_index = 0;
	eq->pop_index = 0;
	eq->size = 0;
}

static sc_integer blink_eventqueue_size(blink_eventqueue * eq)
{
	return eq->size;
}

static blink_event blink_eventqueue_pop(blink_eventqueue * eq)
{
	blink_event event;
	if(blink_eventqueue_size(eq) <= 0) {
		blink_event_init(&event, Blink_invalid_event);
	}
	else {
		event = eq->events[eq->pop_index];
		
		if(eq->pop_index < eq->capacity - 1) {
			eq->pop_index++;
		} 
		else {
			eq->pop_index = 0;
		}
		eq->size--;
	}
	return event;
}
static sc_boolean blink_eventqueue_push(blink_eventqueue * eq, blink_event ev)
{
	if(blink_eventqueue_size(eq) == eq->capacity) {
		return bool_false;
	}
	else {
		eq->events[eq->push_index] = ev;
		
		if(eq->push_index < eq->capacity - 1) {
			eq->push_index++;
		}
		else {
			eq->push_index = 0;
		}
		eq->size++;
		
		return bool_true;
	}
}
static void blink_event_init(blink_event * ev, BlinkEventID name)
{
	ev->name = name;
}

static void blink_add_event_to_queue(blink_eventqueue * eq, BlinkEventID name)
{
	blink_event event;
	blink_event_init(&event, name);
	blink_eventqueue_push(eq, event);
}

static sc_boolean blink_dispatch_event(Blink* handle, const blink_event * event) {
	switch(event->name) {
		case Blink_blink_main_Light__region0_On1_time_event_0:
		{
			handle->timeEvents.blink_main_Light__region0_On1_tev0_raised = bool_true;
			return bool_true;
		}
		case Blink_blink_main_Light__region0_On2_time_event_0:
		{
			handle->timeEvents.blink_main_Light__region0_On2_tev0_raised = bool_true;
			return bool_true;
		}
		case Blink_blink_main_Light__region0_On3_time_event_0:
		{
			handle->timeEvents.blink_main_Light__region0_On3_tev0_raised = bool_true;
			return bool_true;
		}
		case Blink_blink_main_Light__region0_On4_time_event_0:
		{
			handle->timeEvents.blink_main_Light__region0_On4_tev0_raised = bool_true;
			return bool_true;
		}
		case Blink_blink_main_Light__region0_On5_time_event_0:
		{
			handle->timeEvents.blink_main_Light__region0_On5_tev0_raised = bool_true;
			return bool_true;
		}
		case Blink_blink_main_Dark_time_event_0:
		{
			handle->timeEvents.blink_main_Dark_tev0_raised = bool_true;
			return bool_true;
		}
		default:
			return bool_false;
	}
}

static blink_event blink_get_next_event(Blink* handle)
{
	blink_event next_event;
	blink_event_init(&next_event, Blink_invalid_event);
	if(blink_eventqueue_size(&(handle->in_event_queue)) > 0) {
		next_event = blink_eventqueue_pop(&(handle->in_event_queue));
	}
	return next_event;
}

static sc_boolean blink_dispatch_next_event(Blink* handle)
{
	blink_event nextEvent;
	nextEvent = blink_get_next_event(handle);
	return blink_dispatch_event(handle, &nextEvent);
}

static BlinkEventID blink_get_timed_event_name(Blink* handle, sc_eventid evid)
{
	if(evid == &handle->timeEvents.blink_main_Light__region0_On1_tev0_raised) {
		return Blink_blink_main_Light__region0_On1_time_event_0;
	}
	if(evid == &handle->timeEvents.blink_main_Light__region0_On2_tev0_raised) {
		return Blink_blink_main_Light__region0_On2_time_event_0;
	}
	if(evid == &handle->timeEvents.blink_main_Light__region0_On3_tev0_raised) {
		return Blink_blink_main_Light__region0_On3_time_event_0;
	}
	if(evid == &handle->timeEvents.blink_main_Light__region0_On4_tev0_raised) {
		return Blink_blink_main_Light__region0_On4_time_event_0;
	}
	if(evid == &handle->timeEvents.blink_main_Light__region0_On5_tev0_raised) {
		return Blink_blink_main_Light__region0_On5_time_event_0;
	}
	if(evid == &handle->timeEvents.blink_main_Dark_tev0_raised) {
		return Blink_blink_main_Dark_time_event_0;
	}
	return Blink_invalid_event;
}

