/** Generated by itemis CREATE code generator. */


#include "../Inc/sc_types.h"

#include "../Inc/flash.h"
#include "../Inc/flash_required.h"

/*! \file
Implementation of the state machine 'flash'
*/

#ifndef SC_UNUSED
#define SC_UNUSED(P) (void)(P)
#endif

/* prototypes of all internal functions */

/*! State machine reactions. */
static sc_integer react(Flash* handle, const sc_integer transitioned_before);

/*! The reactions of state Light. */
static sc_integer flash_Light_react(Flash* handle, const sc_integer transitioned_before);

/*! The reactions of state Dark. */
static sc_integer flash_Dark_react(Flash* handle, const sc_integer transitioned_before);


static void clear_in_events(Flash* handle);

static void micro_step(Flash* handle);

/*! Performs a 'run to completion' step. */
static void run_cycle(Flash* handle);






static void flash_eventqueue_init(flash_eventqueue * eq, flash_event *buffer, sc_integer capacity);
static sc_integer flash_eventqueue_size(flash_eventqueue * eq);
static void flash_event_init(flash_event * ev, FlashEventID name);
static flash_event flash_eventqueue_pop(flash_eventqueue * eq);
static sc_boolean flash_eventqueue_push(flash_eventqueue * eq, flash_event ev);
static void flash_add_event_to_queue(flash_eventqueue * eq, FlashEventID name);
static sc_boolean flash_dispatch_event(Flash* handle, const flash_event * event);
static flash_event flash_get_next_event(Flash* handle);
static sc_boolean flash_dispatch_next_event(Flash* handle);
static FlashEventID flash_get_timed_event_name(Flash* handle, sc_eventid evid);


void flash_init(Flash* handle)
{
	sc_integer i;
	
	for (i = 0; i < FLASH_MAX_ORTHOGONAL_STATES; ++i)
	{
		handle->stateConfVector[i] = Flash_last_state;
	}
	
				
	clear_in_events(handle);
	
	
	/* Default init sequence for statechart flash */
	flash_set_t_light(handle, 500);
	flash_set_t_dark(handle, 500);
	
	handle->isExecuting = bool_false;
	flash_eventqueue_init(&handle->in_event_queue, handle->in_buffer, FLASH_IN_EVENTQUEUE_BUFFERSIZE);
}

void flash_enter(Flash* handle)
{
	/* Activates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default enter sequence for statechart flash */
	/* 'default' enter sequence for region flash */
	/* Default react sequence for initial entry  */
	/* 'default' enter sequence for state Light */
	/* Entry action for state 'Light'. */
	flash_set_timer(handle, (sc_eventid) &(handle->timeEvents.flash_flash_Light_tev0_raised) , handle->iface.t_light, bool_false);
	flash_switchOn(handle,1);
	flash_switchOn(handle,2);
	flash_switchOn(handle,3);
	handle->stateConfVector[0] = Flash_flash_Light;
	handle->isExecuting = bool_false;
}

void flash_exit(Flash* handle)
{
	/* Deactivates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default exit sequence for statechart flash */
	/* Default exit sequence for region flash */
	/* Handle exit of all possible states (of flash.flash) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Flash_flash_Light :
		{
			/* Default exit sequence for state Light */
			handle->stateConfVector[0] = Flash_last_state;
			/* Exit action for state 'Light'. */
			flash_unset_timer(handle, (sc_eventid) &(handle->timeEvents.flash_flash_Light_tev0_raised) );		
			break;
		}
		case Flash_flash_Dark :
		{
			/* Default exit sequence for state Dark */
			handle->stateConfVector[0] = Flash_last_state;
			/* Exit action for state 'Dark'. */
			flash_unset_timer(handle, (sc_eventid) &(handle->timeEvents.flash_flash_Dark_tev0_raised) );		
			break;
		}
		default: 
			/* do nothing */
			break;
	}
	/* Exit action for state 'flash'. */
	flash_switchOff(handle,1);
	flash_switchOff(handle,2);
	flash_switchOff(handle,3);
	handle->isExecuting = bool_false;
}

/*!
Can be used by the client code to trigger a run to completion step without raising an event.
*/
void flash_trigger_without_event(Flash* handle) {
	run_cycle(handle);
}


sc_boolean flash_is_active(const Flash* handle)
{
	sc_boolean result = bool_false;
	sc_integer i;
	
	for(i = 0; i < FLASH_MAX_ORTHOGONAL_STATES; i++)
	{
		result = result || handle->stateConfVector[i] != Flash_last_state;
	}
	
	return result;
}

/* 
 * Always returns 'false' since this state machine can never become final.
 */
sc_boolean flash_is_final(const Flash* handle)
{
	SC_UNUSED(handle);
	return bool_false;
}

void flash_raise_time_event(Flash* handle, sc_eventid evid)
{
	if ( ((sc_intptr_t)evid) >= ((sc_intptr_t)&(handle->timeEvents))
		&&  ((sc_intptr_t)evid) < ((sc_intptr_t)&(handle->timeEvents)) + (unsigned)sizeof(FlashTimeEvents))
	{
		flash_add_event_to_queue(&(handle->in_event_queue), flash_get_timed_event_name(handle, evid));
		run_cycle(handle);
	}
}

sc_boolean flash_is_state_active(const Flash* handle, FlashStates state)
{
	sc_boolean result = bool_false;
	switch (state)
	{
		case Flash_flash_Light :
			result = (sc_boolean) (handle->stateConfVector[SCVI_FLASH_FLASH_LIGHT] == Flash_flash_Light
			);
				break;
		case Flash_flash_Dark :
			result = (sc_boolean) (handle->stateConfVector[SCVI_FLASH_FLASH_DARK] == Flash_flash_Dark
			);
				break;
			default:
				result = bool_false;
				break;
		}
		return result;
	}

static void clear_in_events(Flash* handle)
{
	handle->timeEvents.flash_flash_Light_tev0_raised = bool_false;
	handle->timeEvents.flash_flash_Dark_tev0_raised = bool_false;
}

static void micro_step(Flash* handle)
{
	switch(handle->stateConfVector[ 0 ])
	{
		case Flash_flash_Light :
		{
			flash_Light_react(handle,-1);
			break;
		}
		case Flash_flash_Dark :
		{
			flash_Dark_react(handle,-1);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
}

static void run_cycle(Flash* handle)
{
	/* Performs a 'run to completion' step. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	flash_dispatch_next_event(handle);
	do
	{ 
		micro_step(handle);
		clear_in_events(handle);
	} while (flash_dispatch_next_event(handle) == bool_true);
	handle->isExecuting = bool_false;
}




sc_integer flash_get_t_light(const Flash* handle)
{
	return handle->iface.t_light;
}
void flash_set_t_light(Flash* handle, sc_integer value)
{
	handle->iface.t_light = value;
}
sc_integer flash_get_t_dark(const Flash* handle)
{
	return handle->iface.t_dark;
}
void flash_set_t_dark(Flash* handle, sc_integer value)
{
	handle->iface.t_dark = value;
}



/* implementations of all internal functions */


static sc_integer react(Flash* handle, const sc_integer transitioned_before)
{
	/* State machine reactions. */
	SC_UNUSED(handle);
	return transitioned_before;
}

static sc_integer flash_Light_react(Flash* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Light. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->timeEvents.flash_flash_Light_tev0_raised == bool_true)
		{ 
			/* Default exit sequence for state Light */
			handle->stateConfVector[0] = Flash_last_state;
			/* Exit action for state 'Light'. */
			flash_unset_timer(handle, (sc_eventid) &(handle->timeEvents.flash_flash_Light_tev0_raised) );		
			handle->timeEvents.flash_flash_Light_tev0_raised = bool_false;
			/* 'default' enter sequence for state Dark */
			/* Entry action for state 'Dark'. */
			flash_set_timer(handle, (sc_eventid) &(handle->timeEvents.flash_flash_Dark_tev0_raised) , handle->iface.t_dark, bool_false);
			flash_switchOff(handle,1);
			flash_switchOff(handle,2);
			flash_switchOff(handle,3);
			handle->stateConfVector[0] = Flash_flash_Dark;
			react(handle,0);
			transitioned_after = 0;
		} 
	} 
	/* If no transition was taken */
	if ((transitioned_after) == (transitioned_before))
	{ 
		/* then execute local reactions. */
		transitioned_after = react(handle,transitioned_before);
	} 
	return transitioned_after;
}

static sc_integer flash_Dark_react(Flash* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Dark. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->timeEvents.flash_flash_Dark_tev0_raised == bool_true)
		{ 
			/* Default exit sequence for state Dark */
			handle->stateConfVector[0] = Flash_last_state;
			/* Exit action for state 'Dark'. */
			flash_unset_timer(handle, (sc_eventid) &(handle->timeEvents.flash_flash_Dark_tev0_raised) );		
			handle->timeEvents.flash_flash_Dark_tev0_raised = bool_false;
			/* 'default' enter sequence for state Light */
			/* Entry action for state 'Light'. */
			flash_set_timer(handle, (sc_eventid) &(handle->timeEvents.flash_flash_Light_tev0_raised) , handle->iface.t_light, bool_false);
			flash_switchOn(handle,1);
			flash_switchOn(handle,2);
			flash_switchOn(handle,3);
			handle->stateConfVector[0] = Flash_flash_Light;
			react(handle,0);
			transitioned_after = 0;
		} 
	} 
	/* If no transition was taken */
	if ((transitioned_after) == (transitioned_before))
	{ 
		/* then execute local reactions. */
		transitioned_after = react(handle,transitioned_before);
	} 
	return transitioned_after;
}




static void flash_eventqueue_init(flash_eventqueue * eq, flash_event *buffer, sc_integer capacity)
{
	eq->events = buffer;
	eq->capacity = capacity;
	eq->push_index = 0;
	eq->pop_index = 0;
	eq->size = 0;
}

static sc_integer flash_eventqueue_size(flash_eventqueue * eq)
{
	return eq->size;
}

static flash_event flash_eventqueue_pop(flash_eventqueue * eq)
{
	flash_event event;
	if(flash_eventqueue_size(eq) <= 0) {
		flash_event_init(&event, Flash_invalid_event);
	}
	else {
		event = eq->events[eq->pop_index];
		
		if(eq->pop_index < eq->capacity - 1) {
			eq->pop_index++;
		} 
		else {
			eq->pop_index = 0;
		}
		eq->size--;
	}
	return event;
}
static sc_boolean flash_eventqueue_push(flash_eventqueue * eq, flash_event ev)
{
	if(flash_eventqueue_size(eq) == eq->capacity) {
		return bool_false;
	}
	else {
		eq->events[eq->push_index] = ev;
		
		if(eq->push_index < eq->capacity - 1) {
			eq->push_index++;
		}
		else {
			eq->push_index = 0;
		}
		eq->size++;
		
		return bool_true;
	}
}
static void flash_event_init(flash_event * ev, FlashEventID name)
{
	ev->name = name;
}

static void flash_add_event_to_queue(flash_eventqueue * eq, FlashEventID name)
{
	flash_event event;
	flash_event_init(&event, name);
	flash_eventqueue_push(eq, event);
}

static sc_boolean flash_dispatch_event(Flash* handle, const flash_event * event) {
	switch(event->name) {
		case Flash_flash_flash_Light_time_event_0:
		{
			handle->timeEvents.flash_flash_Light_tev0_raised = bool_true;
			return bool_true;
		}
		case Flash_flash_flash_Dark_time_event_0:
		{
			handle->timeEvents.flash_flash_Dark_tev0_raised = bool_true;
			return bool_true;
		}
		default:
			return bool_false;
	}
}

static flash_event flash_get_next_event(Flash* handle)
{
	flash_event next_event;
	flash_event_init(&next_event, Flash_invalid_event);
	if(flash_eventqueue_size(&(handle->in_event_queue)) > 0) {
		next_event = flash_eventqueue_pop(&(handle->in_event_queue));
	}
	return next_event;
}

static sc_boolean flash_dispatch_next_event(Flash* handle)
{
	flash_event nextEvent;
	nextEvent = flash_get_next_event(handle);
	return flash_dispatch_event(handle, &nextEvent);
}

static FlashEventID flash_get_timed_event_name(Flash* handle, sc_eventid evid)
{
	if(evid == &handle->timeEvents.flash_flash_Light_tev0_raised) {
		return Flash_flash_flash_Light_time_event_0;
	}
	if(evid == &handle->timeEvents.flash_flash_Dark_tev0_raised) {
		return Flash_flash_flash_Dark_time_event_0;
	}
	return Flash_invalid_event;
}

